# Generated by Django 4.0.5 on 2022-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
