# Generated by Django 4.0.5 on 2022-08-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_agent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='image',
        ),
    ]
