# Generated by Django 4.0.5 on 2022-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_remove_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='realtor'),
        ),
    ]
